### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Vdm88**
Make the initial map bigger.

### CODE REVIEW

**Comment by clydedacruz** [comment]
@Vdm88  wont this push the WKT text box out of the screen ?

**Comment by Vdm88** [comment]
ah.. yes for smaller screens. then let's just put some screen size based heights. For 2K resolution the map is very small.

**Comment by clydedacruz** [comment]
Hmm my screen width is 1366px, but it introduces a scroll. I think the conditions should be based on `min-width`  instead of max-width

**Comment by Vdm88** [comment]
put it how you want it but the same for me .

**Comment by Vdm88** [comment]
ok. i tested with diff resolutions. should work now.

**Comment by clydedacruz** [comment]
Cool. LGTM

**Pull request merged**
